version: '3'

services:
  client:
    build: ./client
    ports:
      - '3000:3000'
  server:
    build: ./server
    ports:
      - '7036:7036'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/app
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0.5
    ports:
      - '27017:27017'
