version: '3'

services:
    client:
        build: ./client
        ports:
            - '3000:3000'
        depends_on:
            - server
    server:
        build: ./server
        ports:
            - '7036:7036'
        volumes:
            - server_data:/app/data
    nginx:
        image: nginx
        ports:
            - '80:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - client
            - server

volumes:
    server_data:
